version: '3.4'

services:
  api:
    image: chrismns/tech-test-mock-server:0.1.0
    ports:
      - "3001:3001"
  web:
    image: siharps/tech-test-web-client:latest
    ports:
      - "3000:3000"
    depends_on:
      - api